Update to November 2021 version (1.2 + fix)
`sudo gem install CocoaPods` doesn't work, and anyone doing this will end up with 
```
gem install CocoaPods
ERROR:  Could not find a valid gem 'CocoaPods' (>= 0) in any repository
```

The correct gem should be `cocoapods` found here: https://rubygems.org/gems/cocoapods
https://github.com/OWASP/owasp-mstg/commit/a2aa3680b0f0d8d1e4cf66ca6b3064006f6fdcb1#diff-99bc45bff94367d5441a4fe2e1ed5d4af9f9005b7ba8f44464697295606f7b27